
name: "Build"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
        
    - name: Install srecord
      run: sudo apt install srecord python3-setuptools
    
    - name: Install nrfutil
      run: sudo -H pip3 install --upgrade pip && sudo -H pip3 install nrfutil 

    - name: make
      run: cd ./firmware && make
